# Sample config file for AWS

FILES:
    -  source: "/var/tmp/authorized-keys"
       destination: "/home/admin/.ssh/authorized-keys"
    -  source: "/var/tmp/trusted-ca.pem"
       destination: "/config/ssl/ssl.crt/trusted-ca.pem"
    -  source: "/var/tmp/custom-file"
       destination: "/config/custom-file"
    -  source: "/var/tmp/f5-declarative-onboarding-1.3.0-4.noarch.rpm"
       destination: "/config/cloud/aws/f5-declaritive-onboarding.rpm"
    -  source: "/var/tmp/f5-appsvcs-3.4.0-2.noarch.rpm"
       destination: "/var/config/rest/downloads/f5-appsvcs.noarch.rpm"

AWS_BUCKET: "my-bucket-name"
AWS_REGION: "us-east-1"

AZURE_STORAGE_CONTAINER_NAME: "my-storage-container-name"

GCE_BUCKET: "my-bucket-name"
